
package com.nibss.nipreport.ws.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NipReportWS", targetNamespace = "http://com.nibss.nipreport.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NipReportWS {


    /**
     * 
     * @param transactionReportBatchId
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "GenerateSettlementReport")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GenerateSettlementReport", targetNamespace = "http://com.nibss.nipreport.ws/", className = "com.nibss.nipreport.ws.impl.GenerateSettlementReport")
    @ResponseWrapper(localName = "GenerateSettlementReportResponse", targetNamespace = "http://com.nibss.nipreport.ws/", className = "com.nibss.nipreport.ws.impl.GenerateSettlementReportResponse")
    @Action(input = "http://com.nibss.nipreport.ws/NipReportWS/GenerateSettlementReportRequest", output = "http://com.nibss.nipreport.ws/NipReportWS/GenerateSettlementReportResponse")
    public boolean generateSettlementReport(
        @WebParam(name = "transactionReportBatchId", targetNamespace = "")
        Long transactionReportBatchId);

    /**
     * 
     * @param transactionReportBatchId
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CompareSettlementReport")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CompareSettlementReport", targetNamespace = "http://com.nibss.nipreport.ws/", className = "com.nibss.nipreport.ws.impl.CompareSettlementReport")
    @ResponseWrapper(localName = "CompareSettlementReportResponse", targetNamespace = "http://com.nibss.nipreport.ws/", className = "com.nibss.nipreport.ws.impl.CompareSettlementReportResponse")
    @Action(input = "http://com.nibss.nipreport.ws/NipReportWS/CompareSettlementReportRequest", output = "http://com.nibss.nipreport.ws/NipReportWS/CompareSettlementReportResponse")
    public boolean compareSettlementReport(
        @WebParam(name = "transactionReportBatchId", targetNamespace = "")
        Long transactionReportBatchId);

    /**
     * 
     * @param transactionReportBatchId
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "GenerateBillingReport")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GenerateBillingReport", targetNamespace = "http://com.nibss.nipreport.ws/", className = "com.nibss.nipreport.ws.impl.GenerateBillingReport")
    @ResponseWrapper(localName = "GenerateBillingReportResponse", targetNamespace = "http://com.nibss.nipreport.ws/", className = "com.nibss.nipreport.ws.impl.GenerateBillingReportResponse")
    @Action(input = "http://com.nibss.nipreport.ws/NipReportWS/GenerateBillingReportRequest", output = "http://com.nibss.nipreport.ws/NipReportWS/GenerateBillingReportResponse")
    public boolean generateBillingReport(
        @WebParam(name = "transactionReportBatchId", targetNamespace = "")
        Long transactionReportBatchId);

    /**
     * 
     * @param transactionReportBatchId
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "PullExcepionLog")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "PullExcepionLog", targetNamespace = "http://com.nibss.nipreport.ws/", className = "com.nibss.nipreport.ws.impl.PullExcepionLog")
    @ResponseWrapper(localName = "PullExcepionLogResponse", targetNamespace = "http://com.nibss.nipreport.ws/", className = "com.nibss.nipreport.ws.impl.PullExcepionLogResponse")
    @Action(input = "http://com.nibss.nipreport.ws/NipReportWS/PullExcepionLogRequest", output = "http://com.nibss.nipreport.ws/NipReportWS/PullExcepionLogResponse")
    public boolean pullExcepionLog(
        @WebParam(name = "transactionReportBatchId", targetNamespace = "")
        Long transactionReportBatchId);

    /**
     * 
     * @param transactionReportBatchId
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "RegenerateSettlementReport")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RegenerateSettlementReport", targetNamespace = "http://com.nibss.nipreport.ws/", className = "com.nibss.nipreport.ws.impl.RegenerateSettlementReport")
    @ResponseWrapper(localName = "RegenerateSettlementReportResponse", targetNamespace = "http://com.nibss.nipreport.ws/", className = "com.nibss.nipreport.ws.impl.RegenerateSettlementReportResponse")
    @Action(input = "http://com.nibss.nipreport.ws/NipReportWS/RegenerateSettlementReportRequest", output = "http://com.nibss.nipreport.ws/NipReportWS/RegenerateSettlementReportResponse")
    public boolean regenerateSettlementReport(
        @WebParam(name = "transactionReportBatchId", targetNamespace = "")
        Long transactionReportBatchId);

}
